// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_expr_stats_cpp
List compute_expr_stats_cpp(const List& logcounts_list, const List& dom_idx_list, int n_genes, int n_domains, int n_cores);
RcppExport SEXP _spaDesign2_compute_expr_stats_cpp(SEXP logcounts_listSEXP, SEXP dom_idx_listSEXP, SEXP n_genesSEXP, SEXP n_domainsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type logcounts_list(logcounts_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type dom_idx_list(dom_idx_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_domains(n_domainsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_expr_stats_cpp(logcounts_list, dom_idx_list, n_genes, n_domains, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// FG_EM_cpp
List FG_EM_cpp(const arma::mat& X, List initial, int iter_max, double tol, int n_cores);
RcppExport SEXP _spaDesign2_FG_EM_cpp(SEXP XSEXP, SEXP initialSEXP, SEXP iter_maxSEXP, SEXP tolSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(FG_EM_cpp(X, initial, iter_max, tol, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// graph_gp_combine_cpp
NumericVector graph_gp_combine_cpp(NumericVector z, IntegerMatrix nn_index, NumericMatrix nn_dist, double rho, bool include_self);
RcppExport SEXP _spaDesign2_graph_gp_combine_cpp(SEXP zSEXP, SEXP nn_indexSEXP, SEXP nn_distSEXP, SEXP rhoSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_index(nn_indexSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nn_dist(nn_distSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_gp_combine_cpp(z, nn_index, nn_dist, rho, include_self));
    return rcpp_result_gen;
END_RCPP
}
// greedy_assign_cpp
IntegerVector greedy_assign_cpp(NumericMatrix query_pts, NumericMatrix ref_pts, IntegerMatrix nn_idx);
RcppExport SEXP _spaDesign2_greedy_assign_cpp(SEXP query_ptsSEXP, SEXP ref_ptsSEXP, SEXP nn_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type query_pts(query_ptsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ref_pts(ref_ptsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_idx(nn_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_assign_cpp(query_pts, ref_pts, nn_idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spaDesign2_compute_expr_stats_cpp", (DL_FUNC) &_spaDesign2_compute_expr_stats_cpp, 5},
    {"_spaDesign2_FG_EM_cpp", (DL_FUNC) &_spaDesign2_FG_EM_cpp, 5},
    {"_spaDesign2_graph_gp_combine_cpp", (DL_FUNC) &_spaDesign2_graph_gp_combine_cpp, 5},
    {"_spaDesign2_greedy_assign_cpp", (DL_FUNC) &_spaDesign2_greedy_assign_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_spaDesign2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
