# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_expr_stats_cpp <- function(logcounts_list, dom_idx_list, n_genes, n_domains, n_cores) {
    .Call(`_spaDesign2_compute_expr_stats_cpp`, logcounts_list, dom_idx_list, n_genes, n_domains, n_cores)
}

FG_EM_cpp <- function(X, initial, iter_max, tol, n_cores = 1L) {
    .Call(`_spaDesign2_FG_EM_cpp`, X, initial, iter_max, tol, n_cores)
}

graph_gp_combine_cpp <- function(z, nn_index, nn_dist, rho, include_self = TRUE) {
    .Call(`_spaDesign2_graph_gp_combine_cpp`, z, nn_index, nn_dist, rho, include_self)
}

greedy_assign_cpp <- function(query_pts, ref_pts, nn_idx) {
    .Call(`_spaDesign2_greedy_assign_cpp`, query_pts, ref_pts, nn_idx)
}

